services:
#  places-svc:
#    build: .
#    container_name: places-svc
#    environment:
#      - KV_VIPER_FILE=./config_docker.yaml
#    ports:
#      - "8004:8000"
#    networks:
#      - chains-net

  places-svc-postgres:
    image: postgis/postgis:16-3.4
    container_name:  places-svc-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "7004:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - chains-net

volumes:
  pgdata:

networks:
  chains-net:
    external: true
